/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type ProfileReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "profile";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  excerpt?: string;
  slug?: Slug;
  coverImage?: ContentImage;
  body?: RichText;
  publishedAt?: string;
  author?: ProfileReference;
  tags?: Array<string>;
  relatedProject?: ProjectReference;
  featured?: boolean;
  seoTitle?: string;
  seoDescription?: string;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ContentImage)
  | {
      language?: string;
      filename?: string;
      code?: string;
      _type: "codeBlock";
      _key: string;
    }
>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContentImage = {
  _type: "contentImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  headline?: string;
  introduction?: string;
  bio?: RichText;
  profileImage?: ContentImage;
  email?: string;
  location?: string;
  resume?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  githubUrl?: string;
  linkedinUrl?: string;
  huggingFaceUrl?: string;
  additionalSocialLinks?: Array<{
    label?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  education?: Array<{
    qualification?: string;
    institution?: string;
    startYear?: number;
    endYear?: number;
    isCurrent?: boolean;
    description?: string;
    _type: "educationEntry";
    _key: string;
  }>;
  projectsCtaText?: string;
  resumeCtaText?: string;
  contactCtaHeading?: string;
  contactCtaText?: string;
  footerTagline?: string;
  footerText?: string;
  siteTitle?: string;
  seoTitle?: string;
  seoDescription?: string;
  socialImage?: ContentImage;
};

export type SkillReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "skill";
};

export type Certification = {
  _id: string;
  _type: "certification";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  provider?: string;
  issueDate?: string;
  credentialId?: string;
  credentialUrl?: string;
  certificateImage?: ContentImage;
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
  featured?: boolean;
};

export type Experience = {
  _id: string;
  _type: "experience";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  role?: string;
  organization?: string;
  employmentType?:
    | "full-time"
    | "part-time"
    | "internship"
    | "contract"
    | "freelance"
    | "self-employed"
    | "volunteer";
  startDate?: string;
  isCurrent?: boolean;
  endDate?: string;
  location?: string;
  workplaceType?: "remote" | "hybrid" | "on-site";
  description?: string;
  responsibilities?: Array<string>;
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
  organizationLogo?: ContentImage;
  externalUrl?: string;
};

export type ProjectCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projectCategory";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  summary?: string;
  primaryCategory?: ProjectCategoryReference;
  technologies?: Array<
    {
      _key: string;
    } & SkillReference
  >;
  slug?: Slug;
  coverImage?: ContentImage;
  projectDate?: string;
  featured?: boolean;
  tags?: Array<string>;
  problem?: RichText;
  objective?: RichText;
  approach?: RichText;
  content?: RichText;
  results?: RichText;
  metrics?: Array<{
    label?: string;
    value?: string;
    context?: string;
    _type: "metric";
    _key: string;
  }>;
  screenshots?: Array<
    {
      _key: string;
    } & ContentImage
  >;
  challenges?: RichText;
  whatILearned?: RichText;
  githubUrl?: string;
  liveDemoUrl?: string;
  huggingFaceUrl?: string;
  notebookUrl?: string;
  datasetUrl?: string;
  videoUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
};

export type Skill = {
  _id: string;
  _type: "skill";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  category?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  displayOrder?: number;
  featured?: boolean;
  level?: "foundational" | "working-knowledge" | "proficient" | "advanced";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ProjectCategory = {
  _id: string;
  _type: "projectCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  displayOrder?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProfileReference
  | ProjectReference
  | BlogPost
  | RichText
  | SanityImageAssetReference
  | ContentImage
  | Slug
  | SanityFileAssetReference
  | Profile
  | SkillReference
  | Certification
  | Experience
  | ProjectCategoryReference
  | Project
  | Skill
  | SanityImageCrop
  | SanityImageHotspot
  | ProjectCategory
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: PROJECT_CATEGORIES_QUERY
// Query: *[_type == "projectCategory"]  | order(coalesce(displayOrder, 2147483647) asc, title asc, _id asc) {    _id,    title,    "slug": slug.current,    description,    displayOrder  }
export type PROJECT_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  displayOrder: number | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"]  | order(coalesce(displayOrder, 2147483647) asc, name asc, _id asc) {    _id,    name,    category,    displayOrder,    "featured": coalesce(featured, false),    level,    icon {      _type,      asset,      alt,      crop,      hotspot    }  }
export type SKILLS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  category: string | null;
  displayOrder: number | null;
  featured: boolean | false;
  level:
    "advanced" | "foundational" | "proficient" | "working-knowledge" | null;
  icon: {
    _type: "image";
    asset: SanityImageAssetReference | null;
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile" && _id == $profileId][0] {    _id,    name,    headline,    introduction,    bio,    profileImage,    email,    location,    resume {      asset-> {        _id,        url,        originalFilename,        mimeType,        size      }    },    githubUrl,    linkedinUrl,    huggingFaceUrl,    additionalSocialLinks,    education,    projectsCtaText,    resumeCtaText,    contactCtaHeading,    contactCtaText,    footerTagline,    footerText,    siteTitle,    seoTitle,    seoDescription,    socialImage  }
export type PROFILE_QUERY_RESULT = {
  _id: string;
  name: string | null;
  headline: string | null;
  introduction: string | null;
  bio: RichText | null;
  profileImage: ContentImage | null;
  email: string | null;
  location: string | null;
  resume: {
    asset: {
      _id: string;
      url: string | null;
      originalFilename: string | null;
      mimeType: string | null;
      size: number | null;
    } | null;
  } | null;
  githubUrl: string | null;
  linkedinUrl: string | null;
  huggingFaceUrl: string | null;
  additionalSocialLinks: Array<{
    label?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
  education: Array<{
    qualification?: string;
    institution?: string;
    startYear?: number;
    endYear?: number;
    isCurrent?: boolean;
    description?: string;
    _type: "educationEntry";
    _key: string;
  }> | null;
  projectsCtaText: string | null;
  resumeCtaText: string | null;
  contactCtaHeading: string | null;
  contactCtaText: string | null;
  footerTagline: string | null;
  footerText: string | null;
  siteTitle: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  socialImage: ContentImage | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"]  | order(projectDate desc, _id asc) {    _id,    title,    summary,    "slug": slug.current,    coverImage,    projectDate,    "featured": coalesce(featured, false),    tags,    primaryCategory-> {      _id,      title,      "slug": slug.current    },    technologies[]-> {      _id,      name,      category    }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  summary: string | null;
  slug: string | null;
  coverImage: ContentImage | null;
  projectDate: string | null;
  featured: boolean | false;
  tags: Array<string> | null;
  primaryCategory: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: string | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && defined(slug.current) && slug.current == $slug]  | order(_id asc) [0] {    _id,    title,    summary,    "slug": slug.current,    coverImage,    projectDate,    "featured": coalesce(featured, false),    tags,    primaryCategory-> {      _id,      title,      "slug": slug.current    },    technologies[]-> {      _id,      name,      category    },    problem,    objective,    approach,    content,    results,    metrics,    screenshots,    challenges,    whatILearned,    githubUrl,    liveDemoUrl,    huggingFaceUrl,    notebookUrl,    datasetUrl,    videoUrl,    seoTitle,    seoDescription  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  summary: string | null;
  slug: string | null;
  coverImage: ContentImage | null;
  projectDate: string | null;
  featured: boolean | false;
  tags: Array<string> | null;
  primaryCategory: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  technologies: Array<{
    _id: string;
    name: string | null;
    category: string | null;
  }> | null;
  problem: RichText | null;
  objective: RichText | null;
  approach: RichText | null;
  content: RichText | null;
  results: RichText | null;
  metrics: Array<{
    label?: string;
    value?: string;
    context?: string;
    _type: "metric";
    _key: string;
  }> | null;
  screenshots: Array<
    {
      _key: string;
    } & ContentImage
  > | null;
  challenges: RichText | null;
  whatILearned: RichText | null;
  githubUrl: string | null;
  liveDemoUrl: string | null;
  huggingFaceUrl: string | null;
  notebookUrl: string | null;
  datasetUrl: string | null;
  videoUrl: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: BLOG_POSTS_QUERY
// Query: *[_type == "blogPost" && defined(slug.current)]  | order(publishedAt desc, _id asc) {    _id,    title,    excerpt,    "slug": slug.current,    coverImage,    publishedAt,    tags,    "featured": coalesce(featured, false),    author-> {      _id,      name    }  }
export type BLOG_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  excerpt: string | null;
  slug: string | null;
  coverImage: ContentImage | null;
  publishedAt: string | null;
  tags: Array<string> | null;
  featured: boolean | false;
  author: {
    _id: string;
    name: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: BLOG_POST_BY_SLUG_QUERY
// Query: *[_type == "blogPost" && defined(slug.current) && slug.current == $slug]  | order(_id asc) [0] {    _id,    title,    excerpt,    "slug": slug.current,    coverImage,    body,    publishedAt,    tags,    "featured": coalesce(featured, false),    author-> {      _id,      name,      headline,      profileImage    },    relatedProject-> {      _id,      title,      summary,      "slug": slug.current,      coverImage    },    seoTitle,    seoDescription  }
export type BLOG_POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  excerpt: string | null;
  slug: string | null;
  coverImage: ContentImage | null;
  body: RichText | null;
  publishedAt: string | null;
  tags: Array<string> | null;
  featured: boolean | false;
  author: {
    _id: string;
    name: string | null;
    headline: string | null;
    profileImage: ContentImage | null;
  } | null;
  relatedProject: {
    _id: string;
    title: string | null;
    summary: string | null;
    slug: string | null;
    coverImage: ContentImage | null;
  } | null;
  seoTitle: string | null;
  seoDescription: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"]  | order(coalesce(isCurrent, false) desc, startDate desc, _id asc) {    _id,    role,    organization,    employmentType,    startDate,    endDate,    "isCurrent": coalesce(isCurrent, false),    location,    workplaceType,    description,    responsibilities,    skills[]-> {      _id,      name,      category    },    organizationLogo,    externalUrl  }
export type EXPERIENCE_QUERY_RESULT = Array<{
  _id: string;
  role: string | null;
  organization: string | null;
  employmentType:
    | "contract"
    | "freelance"
    | "full-time"
    | "internship"
    | "part-time"
    | "self-employed"
    | "volunteer"
    | null;
  startDate: string | null;
  endDate: string | null;
  isCurrent: boolean | false;
  location: string | null;
  workplaceType: "hybrid" | "on-site" | "remote" | null;
  description: string | null;
  responsibilities: Array<string> | null;
  skills: Array<{
    _id: string;
    name: string | null;
    category: string | null;
  }> | null;
  organizationLogo: ContentImage | null;
  externalUrl: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: CERTIFICATIONS_QUERY
// Query: *[_type == "certification"]  | order(coalesce(featured, false) desc, issueDate desc, _id asc) {    _id,    title,    provider,    issueDate,    credentialId,    credentialUrl,    certificateImage,    skills[]-> {      _id,      name,      category    },    "featured": coalesce(featured, false)  }
export type CERTIFICATIONS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  provider: string | null;
  issueDate: string | null;
  credentialId: string | null;
  credentialUrl: string | null;
  certificateImage: ContentImage | null;
  skills: Array<{
    _id: string;
    name: string | null;
    category: string | null;
  }> | null;
  featured: boolean | false;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "projectCategory"]\n  | order(coalesce(displayOrder, 2147483647) asc, title asc, _id asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    displayOrder\n  }\n': PROJECT_CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "skill"]\n  | order(coalesce(displayOrder, 2147483647) asc, name asc, _id asc) {\n    _id,\n    name,\n    category,\n    displayOrder,\n    "featured": coalesce(featured, false),\n    level,\n    icon {\n      _type,\n      asset,\n      alt,\n      crop,\n      hotspot\n    }\n  }\n': SKILLS_QUERY_RESULT;
    '\n  *[_type == "profile" && _id == $profileId][0] {\n    _id,\n    name,\n    headline,\n    introduction,\n    bio,\n    profileImage,\n    email,\n    location,\n    resume {\n      asset-> {\n        _id,\n        url,\n        originalFilename,\n        mimeType,\n        size\n      }\n    },\n    githubUrl,\n    linkedinUrl,\n    huggingFaceUrl,\n    additionalSocialLinks,\n    education,\n    projectsCtaText,\n    resumeCtaText,\n    contactCtaHeading,\n    contactCtaText,\n    footerTagline,\n    footerText,\n    siteTitle,\n    seoTitle,\n    seoDescription,\n    socialImage\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project"]\n  | order(projectDate desc, _id asc) {\n    _id,\n    title,\n    summary,\n    "slug": slug.current,\n    coverImage,\n    projectDate,\n    "featured": coalesce(featured, false),\n    tags,\n    primaryCategory-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n    technologies[]-> {\n      _id,\n      name,\n      category\n    }\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current) && slug.current == $slug]\n  | order(_id asc) [0] {\n    _id,\n    title,\n    summary,\n    "slug": slug.current,\n    coverImage,\n    projectDate,\n    "featured": coalesce(featured, false),\n    tags,\n    primaryCategory-> {\n      _id,\n      title,\n      "slug": slug.current\n    },\n    technologies[]-> {\n      _id,\n      name,\n      category\n    },\n    problem,\n    objective,\n    approach,\n    content,\n    results,\n    metrics,\n    screenshots,\n    challenges,\n    whatILearned,\n    githubUrl,\n    liveDemoUrl,\n    huggingFaceUrl,\n    notebookUrl,\n    datasetUrl,\n    videoUrl,\n    seoTitle,\n    seoDescription\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "blogPost" && defined(slug.current)]\n  | order(publishedAt desc, _id asc) {\n    _id,\n    title,\n    excerpt,\n    "slug": slug.current,\n    coverImage,\n    publishedAt,\n    tags,\n    "featured": coalesce(featured, false),\n    author-> {\n      _id,\n      name\n    }\n  }\n': BLOG_POSTS_QUERY_RESULT;
    '\n  *[_type == "blogPost" && defined(slug.current) && slug.current == $slug]\n  | order(_id asc) [0] {\n    _id,\n    title,\n    excerpt,\n    "slug": slug.current,\n    coverImage,\n    body,\n    publishedAt,\n    tags,\n    "featured": coalesce(featured, false),\n    author-> {\n      _id,\n      name,\n      headline,\n      profileImage\n    },\n    relatedProject-> {\n      _id,\n      title,\n      summary,\n      "slug": slug.current,\n      coverImage\n    },\n    seoTitle,\n    seoDescription\n  }\n': BLOG_POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "experience"]\n  | order(coalesce(isCurrent, false) desc, startDate desc, _id asc) {\n    _id,\n    role,\n    organization,\n    employmentType,\n    startDate,\n    endDate,\n    "isCurrent": coalesce(isCurrent, false),\n    location,\n    workplaceType,\n    description,\n    responsibilities,\n    skills[]-> {\n      _id,\n      name,\n      category\n    },\n    organizationLogo,\n    externalUrl\n  }\n': EXPERIENCE_QUERY_RESULT;
    '\n  *[_type == "certification"]\n  | order(coalesce(featured, false) desc, issueDate desc, _id asc) {\n    _id,\n    title,\n    provider,\n    issueDate,\n    credentialId,\n    credentialUrl,\n    certificateImage,\n    skills[]-> {\n      _id,\n      name,\n      category\n    },\n    "featured": coalesce(featured, false)\n  }\n': CERTIFICATIONS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
